services:
  - type: web
    name: aniweb
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        generateValue: true
